#!/bin/bash

rm /opt/karaf/firstboot


if [[ "${CLEAN_CACHE}" = "true" || "${CLEAN_CACHE}" = "TRUE" ]]
then
  rm -rf /opt/karaf/data/cache
fi

if [ ! -z "${FETCH_CUSTOM_URL}" ]
then
    if [ "${FETCH_CUSTOM_URL}" != "NONE" ]
    then
        wget ${FETCH_CUSTOM_URL} -P /opt/karaf/etc
    fi
fi

if [ ! -d "/opt/karaf/vol/etc" ]
then
   mkdir /opt/karaf/vol/etc
fi

if [ ! -d "/opt/karaf/vol/bin" ]
then
   mkdir /opt/karaf/vol/bin
fi

if [ ! -d "/opt/karaf/vol/backup" ]
then
   mkdir /opt/karaf/vol/backup
fi

cp /opt/karaf/etc_original.tgz /opt/karaf/vol/backup/


/opt/karaf/bin/volumelinker LINK_VOL_DEPLOY /deploy /deploy 
/opt/karaf/bin/volumelinker LINK_VOL_LOG /data/log /log
/opt/karaf/bin/volumelinker LINK_VOL_TMP /data/tmp /tmp

if [ -f  "/opt/karaf/bin/initkarafcustom" ]
then
    /opt/karaf/bin/initkarafcustom >> /opt/karaf/data/log/initkarafcustom.log 2>&1 &
fi


if [ ! -z "${KARAF_INIT_COMMANDS}" ]
then
    if [ "${KARAF_INIT_COMMANDS}" != "NONE" ]
    then
        echo ${KARAF_INIT_COMMANDS} > /opt/karaf/bin/initcommands
        /opt/karaf/bin/varinitrunner  >> /opt/karaf/data/log/initcommands.log 2>&1 &
    fi
fi


if [ -f  /opt/karaf/vol/bin/initcommands ]
then
    /opt/karaf/bin/fileinitrunner >> /opt/karaf/data/log/initcommands.log 2>&1 &
fi

