name: Publish Docker image

on:
  push:
    branches:
      # Push events on main branch
      - main
    tags:
      - v*

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - 
        name: Publish Action
        uses: actions/publish-docker-image-to-ghcr-io@latest
        with:
          dockerName: 'karab-base'
